export interface ProductData {
    id: number;
    brand: string;
    name: string;
    description: string;
    price: number;
    image: string;
  }
  
  const products: ProductData[] = [
    {
      id: 1,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/2.jpeg',
    },
    {
      id: 2,
      brand: 'Converse',
      name: 'Converse',
      description: 'Run Star Hike Three Color Unisex ',
      price: 85.5,
      image: './image/3.jpeg',
    },
    {
      id: 3,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Jordan 1 Retro High Obsidian UNC',
      price: 196,
      image: './image/4.jpeg',
    },
    {
      id: 4,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Shadow Beige Pale Ivory',
      price: 115,
      image: './image/1.jpeg',
    },
    {
      id: 5,
      brand: 'NewBalance',
      name: 'NewBalance',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/5.jpeg',
    },
    {
      id: 6,
      brand: 'Asics',
      name: 'Asics',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/6.jpeg',
    },
    {
      id: 7,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/2.jpeg',
    },
    {
      id: 8,
      brand: 'Converse',
      name: 'Converse',
      description: 'Run Star Hike Three Color Unisex',
      price: 85.5,
      image: './image/3.jpeg',
    },
    {
      id: 9,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Shadow Beige Pale Ivory',
      price: 96,
      image: './image/4.jpeg',
    },
    {
      id: 10,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Jordan 1 Retro High Obsidian UNC',
      price: 96,
      image: './image/1.jpeg',
    },
    {
      id: 11,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/2.jpeg',
    },
    {
      id: 12,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/2.jpeg',
    },
    {
      id: 13,
      brand: 'Converse',
      name: 'Converse',
      description: 'Run Star Hike Three Color Unisex ',
      price: 85.5,
      image: './image/3.jpeg',
    },
    {
      id: 14,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Jordan 1 Retro High Obsidian UNC',
      price: 96,
      image: './image/4.jpeg',
    },
    {
      id: 15,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Shadow Beige Pale Ivory',
      price: 96,
      image: './image/1.jpeg',
    },
    {
      id: 16,
      brand: 'NewBalance',
      name: 'NewBalance',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/5.jpeg',
    },
    {
      id: 17,
      brand: 'Asics',
      name: 'Asics',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/6.jpeg',
    },
    {
      id: 18,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/2.jpeg',
    },
    {
      id: 19,
      brand: 'Converse',
      name: 'Converse',
      description: 'Run Star Hike Three Color Unisex',
      price: 85.5,
      image: './image/3.jpeg',
    },
    {
      id: 20,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Jordan 1 Retro High Obsidian UNC',
      price: 96,
      image: './image/4.jpeg',
    },
    {
      id: 21,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Shadow Beige Pale Ivory',
      price: 96,
      image: './image/1.jpeg',
    },
    {
      id: 22,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/2.jpeg',
    },
    {
      id: 23,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Force 1 Jester XX Black Sonic Yellow',
      price: 96,
      image: './image/2.jpeg',
    },
    {
      id: 24,
      brand: 'Converse',
      name: 'Converse',
      description: 'Run Star Hike Three Color Unisex ',
      price: 85.5,
      image: './image/3.jpeg',
    },
    {
      id: 25,
      brand: 'Nike',
      name: 'Nike',
      description: 'Air Jordan 1 Retro High Obsidian UNC',
      price: 96,
      image: './image/4.jpeg',
    }
  ];
  
  export const getAllProducts = (): ProductData[] => {
    return products;
  };
  